### ISSUE TITLE
license ?

### ISSUE THREAD

**Issue by trebmuh** [dmitrysmagin/a2t_play#1]
I didn't find a license file for this software. Can you please tell me what it's?

**Comment by dmitrysmagin** [comment]
As it's derived from http://www.adlibtracker.net/ code it has the same license, LGPL2.1
Sorry for not including the license file.

**Comment by trebmuh** [comment]
Thanks for your quick answer.

**Comment by dmitrysmagin** [comment]
Take care if you are going to use this code. It kind of works and plays fine, but there could be some bugs. The code is a direct port from Pascal and is very ugly. :)

**Comment by trebmuh** [comment]
OK, thanks for the info.
