### ISSUE TITLE
Cannot play version 1 songs

### ISSUE THREAD

**Issue by tomas** [dmitrysmagin/a2t_play#3]
Hi, I just compiled and tried to play a v1 song but got an ugly segfault, which I narrowed down to the sixpack logic. I managed to get that part working, but the output I get from the song isn't right (notes/tempo/effects). I was wondering if you had tested any v1 songs so far and if you had had better results.

The song I'm testing is MARIO.A2M from [here](https://github.com/adplug/adplug/tree/master/test).

**Comment by dmitrysmagin** [comment]
Thanks, I'll check this out. Adlibtracker 2 is notorious for using modified pack/depack algos :(
I haven't tested much v1 files, sorry.

**Comment by dmitrysmagin** [comment]
I figured out the problem. The file you pointed (MARIO.A2M) contains rubbish in place of block lengths
![изображение](https://user-images.githubusercontent.com/2268825/105711120-255bc080-5f29-11eb-947e-d800f99a4ee6.png)
Perhaps, some older Adlibtracker version didn't clear the buffers correctly when writing data.

**Comment by tomas** [comment]
Somehow adplug manages to play it just fine though... :)

Are you sure that is rubbish and not part of the original spec?

**Comment by dmitrysmagin** [comment]
Yes, pretty sure. I've made a quick fix and the crash is gone, however, the notes and effects are indeed a bit weird, because they have to be converted to later versions. Will be fixed soon.

**Comment by tomas** [comment]
Great! Thanks

**Comment by dmitrysmagin** [comment]
Updated, this commit allows to load v1,2,3,4 a2m:
https://github.com/dmitrysmagin/a2t_play/commit/50b8de0d52af56a6235d1aad9e3c03f1657ec8e0
At least, MARIO.A2M now sounds correctly.
Moreover, I need to update the whole player/loader, because it's rather outdated and doesn't play latest v14 correctly as well.

**Comment by tomas** [comment]
Wow, that was fast. Great work!
